version: '3.8'
services:
  chat:
    image: ollama/ollama:latest
    command: ["run","llama3:8b-instruct"]
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/ollama/data

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      TTS_BACKEND: local
      PIPER_VOICE: pt-br-joaquim-low
      OLLAMA_URL: http://chat:11434/api/chat
    depends_on:
      - chat

volumes:
  ollama_data:
